version: "3.7"
services:
  app:
    build:
      args:
        user: teste-revendamais
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teste-revendamais-image
    container_name: teste-revendamais-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teste-revendamais-network
  db:
    image: mysql:8.0
    container_name: teste-revendamais-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - teste-revendamais-network
  nginx:
    image: nginx:alpine
    container_name: teste-revendamais-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - teste-revendamais-network
networks:
  teste-revendamais-network:
    driver: bridge
volumes:
  mysql_data: